let users = [
  {
    id: 1,
    name: "علی رضایی",
    job: "برنامه نویس",
    projects: 7,
    income: 1200,
    platform: "upwork",
    permission: "user",
  },
  {
    id: 2,
    name: "محمد حسینی",
    job: "طراح وب",
    projects: 4,
    income: 800,
    platform: "upwork",
    permission: "user",
  },
  {
    id: 3,
    name: "سارا مهری",
    job: "مدیر پروژه",
    projects: 6,
    income: 1500,
    platform: "upwork",
    permission: "user",
  },
  {
    id: 4,
    name: "فاطمه اکبری",
    job: "ترجمه",
    projects: 3,
    income: 600,
    platform: "upwork",
    permission: "user",
  },
  {
    id: 5,
    name: "حسن رحیمی",
    job: "توسعه دهنده اپلیکیشن",
    projects: 5,
    income: 1100,
    platform: "fiverr",
    permission: "user",
  },
  {
    id: 6,
    name: "زهرا محمدی",
    job: "توسعه دهنده وب",
    projects: 3,
    income: 750,
    platform: "fiverr",
    permission: "user",
  },
  {
    id: 7,
    name: "محمدرضا عبدی",
    job: "مهندسی نرم‌افزار",
    projects: 8,
    income: 1600,
    platform: "fiverr",
    permission: "user",
  },
  {
    id: 8,
    name: "سمانه خضری",
    job: "توسعه دهنده موبایل",
    projects: 4,
    income: 900,
    platform: "fiverr",
    permission: "user",
  },
  {
    id: 9,
    name: "علیرضا قاسمی",
    job: "مدیریت پروژه",
    projects: 7,
    income: 1400,
    platform: "fiverr",
    permission: "user",
  },
  {
    id: 10,
    name: "پریسا صدیقی",
    job: "توسعه دهنده وب",
    projects: 6,
    income: 1250,
    platform: "fiverr",
    permission: "user",
  },
  {
    id: 11,
    name: "عباس ملاولی",
    job: "برنامه نویسی",
    projects: 3,
    income: 890,
    platform: "amazon",
    permission: "user",
  },
  {
    id: 12,
    name: "حسین رحمانی",
    job: "توسعه دهنده اپلیکیشن",
    projects: 5,
    income: 1200,
    platform: "amazon",
    permission: "user",
  },
  {
    id: 13,
    name: "مریم احمدی",
    job: "مدیر پروژه",
    projects: 2,
    income: 500,
    platform: "amazon",
    permission: "user",
  },
  {
    id: 14,
    name: "لیلا صفری",
    job: "طراح وب",
    projects: 4,
    income: 950,
    platform: "amazon",
    permission: "user",
  },
  {
    id: 15,
    name: "مهدی محمدی",
    job: "ترجمه",
    projects: 6,
    income: 1300,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 16,
    name: "نازنین جعفری",
    job: "توسعه دهنده وب",
    projects: 3,
    income: 750,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 17,
    name: "علی حسنی",
    job: "مهندسی نرم‌افزار",
    projects: 5,
    income: 1100,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 18,
    name: "زهرا ابراهیمی",
    job: "توسعه دهنده موبایل",
    projects: 3,
    income: 800,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 19,
    name: "محمدرضا رستمی",
    job: "مدیریت پروژه",
    projects: 8,
    income: 1600,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 20,
    name: "محمد علوی",
    job: "توسعه دهنده وب",
    projects: 4,
    income: 950,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 41,
    name: "رضا احمدی",
    job: "طراح گرافیک",
    projects: 5,
    income: 900,
    platform: "upwork",
    permission: "user",
  },
  {
    id: 42,
    name: "نیلوفر رضایی",
    job: "مترجم",
    projects: 4,
    income: 700,
    platform: "upwork",
    permission: "user",
  },
  {
    id: 43,
    name: "محمد زارعی",
    job: "توسعه دهنده اپلیکیشن",
    projects: 6,
    income: 1250,
    platform: "fiverr",
    permission: "user",
  },
  {
    id: 44,
    name: "فاطمه موسوی",
    job: "توسعه دهنده وب",
    projects: 5,
    income: 1100,
    platform: "fiverr",
    permission: "user",
  },
  {
    id: 45,
    name: "سعید قربانی",
    job: "مهندس معماری",
    projects: 7,
    income: 1500,
    platform: "amazon",
    permission: "user",
  },
  {
    id: 46,
    name: "زینب رحیمی",
    job: "نویسنده",
    projects: 3,
    income: 600,
    platform: "amazon",
    permission: "user",
  },
  {
    id: 47,
    name: "علی اکبری",
    job: "طراح وب",
    projects: 5,
    income: 1000,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 48,
    name: "حسین رستمی",
    job: "توسعه دهنده موبایل",
    projects: 4,
    income: 850,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 49,
    name: "مریم کریمی",
    job: "مدیریت پروژه",
    projects: 6,
    income: 1300,
    platform: "peopleperhour",
    permission: "user",
  },
  {
    id: 50,
    name: "ناصر جعفری",
    job: "برنامه نویس",
    projects: 8,
    income: 1600,
    platform: "peopleperhour",
    permission: "user",
  },
];

export { users };
